### ISSUE TITLE
Messages do not consistently update 'live', but do appear on browser refresh

### ISSUE THREAD

**Issue by dwblair** [cabal-club/message-land#2]

**Comment by dwblair** [comment]
Oh, apologies -- this might be because I'm using two tabs in the same browser to test sending messages back and forth -- I realized that it's marking me as the same 'entity'.  I will test with different browsers ...

**Comment by dwblair** [comment]
Ah, interesting ...

So, I've got a friend in CA, USA ... and then a server based in NY ... and then one locally.  Not all messages that I'm sending via cabal are always appearing in the glitch app immediately -- but it does seem as though eventually some of them have appeared and inserted themselves properly into the timeline.  So cool.

**Comment by joehand** [comment]
Ya the websocket connect seems to cut in and out a lot. The glitch server is hitting the memory limit pretty quickly now, so restarts often. You can "remix" it to get your own server =), should all work otta the box you just get your own url!

**Comment by dwblair** [comment]
@joehand -- this is *such* a great thing you're doing here -- I'm trying to get some folks from my community to test out cabal, and being able to use the web app makes it super easy. Thank you!!

**Comment by dwblair** [comment]
Update -- used 'remix' to spin up my own server, and it seemed to be more stable. This is so cool.  I'm going to try to spin this code up on a digital ocean server too.

It's a really easy on-ramp to cabal; and also, I suppose, can serve the role of offering a 'superpeer' online, which is more consistently online, eh?
